config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root "pins#index"
  get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
      validates :image, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :pins     
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about 
  end 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
   @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
    pin = Pin.find params[:id]
    @description = pin.description
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      # Sending email
      # AdvertMailer.advert_email.deliver_now
      redirect_to @pin, notice: 'Your Advert was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Your Advert was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this advert" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!-- <%= link_to "Adverts.Market" , root_path, class: "navbar-brand" %>  -->
    <!-- Logo below is not sizing properly, need assistance-->
    <%= link_to image_tag("95703_Adverts_logo_PA_1 (1).png") , root_path, class: "navbar-brand" %>  
    
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Print Ad
            <% end %>
          </li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          
        <% end %>
        
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adverts Market</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

 
     <%= render 'layouts/header' %>
     
     <div class="container">
    <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>     
          <%= yield %>
          

    </div>

</body>

</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Welcome to Adverts.Market</h1>
  <h2>Print Ads Made Easy</h2>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb
<h1>About US</h1>
<div class="jumbotron">
<p><strong> Book cost effective print advertising in minutes</strong></p>

Adverts Market is an online marketplace that allows advertisers to run newspaper and print ads in daily and weekly newspapers.  
Whether you’re advertising your business in small 1 column by 2 inch ads or large quarter or full page ads, we have a solution for you.
<br>
Traditionally, buying newspaper advertising space is a labor-intensive process involving numerous phone calls, discussion of column inches and rates cards and other specs. With a simple online portal, Adverts Market makes it easier to plan, procure and traffic newspaper advertising through a <strong>web-based</strong> interface.
<br>
<strong>Why Newspapers?</strong>
<br>
Newspaper advertising is a great complement to Digital, allowing you to expand the reach of your marketing campaigns.
<br>
In fact, every day about 50% of Americans reads a newspaper.  On Sunday, that number increases -- beyond the reach of the Superbowl.
+ Newspaper ads are considered trustworthy, more than any other medium,
+ 85% of readers say they have bought something advertised in the newspaper.
+ and Readers are highly engaged when reading the newspaper
<br>
Newspapers allow you to communicate to your target customers in a rich display format, whether you want to announce a promotion or sale, generate awareness for a new product, or change customer perceptions of your company or brand.
<br>
<strong>Here’s how Adverts Market works:</strong>
<br>
First, you need an account. Log into Adverts.Market and search for newspapers by city or state or enter a newspaper name or restrict your search by circulation, newspaper section, ad size or publication type.
<br>
We’ve partnered with over 600 newspapers across the globe that have an with aggregate circulation of over 36 million. 
Including large newspapers like The New York Times, LA Times, San Francisco Chronicle and Washington Post as well as  smaller community newspapers, college papers, free dailies, Spanish-language papers, and weeklies.
<br>
Compare the newspapers by circulation and, and then select the newspapers you want.
<br>
Then select desired section of the newspaper, ad size, and days of the week.
<br>
You’ll see the newspapers listed rate price on the right.  Then name your “bid” – the price you’re willing to pay for the ad insertion.
<br>
You can also set a campaign budget, and you’ll only be charged up to the budget you set.
<br>
Adverts.Market isn't an auction --  so you are not competing with other advertisers for ad space.
Instead, your offer will be reviewed individually by the newspaper
<br>
Publishers will respond (generally, within a day or two) by accepting your bid or initiating discussions about why your bid was not accepted. 
<br>
  If you bid is rejected, the publisher may provide feedback and you can choose to submit new bids based on these discussions.
<br>
  If your bid is accepted, you upload your B&W ad and the newspaper publisher prints your ad.
<br>
If you have your own ad, you can upload it into Adverts.Market.
<br>
Don’t have an ad?  Don’t worry, you can create an ad in minutes using our ad creation tools.  Just enter text and upload an image or logo. Then we’ll generate several layouts for you to choose from.
<br>
<br>
Finally, once your ads are published, you’ll be able to download and view electronic copies of your ads as they were printed on the page.
<br>
<br>
Ready to reach new customers with newspaper ads?
 Try Adverts Market today - print ads made easy.








</p>
</div>

app/views/pins/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>
      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title, value: "Title" %>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :description, value: "Advert text/copy" %> 
    <%= f.cktext_area :description, :value => @description, :id => 'sometext' %>
  </div>

  (Click on "Create Ad" button is going to send an email to user(s))
  <br></br>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary", value: "Create Ad" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Advert</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div id="pins" class="transitions-enabled">
  <% if user_signed_in? %>
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.email if pin.user %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
        <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Print Advert</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
		<div class="panel-heading center">
			<%= image_tag @pin.image.url(:medium) %>
		</div>
		<div class="panel-body">
		<p><%= raw(@pin.title) %></p>
		<p><strong><%= @pin.user.name if @pin.user %></strong></p>

		<% if @pin.user == current_user %>
			<%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
		<% end %>
		</div>
	</div>

</div>